# https://github.com/release-it/release-it/blob/master/config/release-it.json
git:
  commitMessage: 'chore: release v${version}'
github:
  release: true
  releaseName: 'v${version}'
npm:
  publish: false
hooks: # https://github.com/release-it/release-it#hooks
  before:release:
    - docker build --no-cache -t uetchy/umami .
    - docker tag uetchy/umami uetchy/umami:${version}
    - docker push uetchy/umami
    - docker push uetchy/umami:${version}
