version: '3.1'

services:
  app:
    image: uetchy/umami:latest
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/umami
      HASH_SALT: ${HASH_SALT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: umami
    volumes:
      - ./umami/sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/init.sql
      - ${UMAMI_DB_DIR}:/var/lib/postgresql/data
networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
